### ISSUE TITLE
Configuration in OpenVPN as Proxy?

### ISSUE THREAD

**Issue by lordnik22** [pelzvieh/IPv6Droid#53]
Hello,

I was able to connect and obtain an IPv6 with your app.
Tested with ping6 and termux

After this I tried to configure a proxy in OpenVPN with the Server's IP that I see in the "statistics-view"(IPv6Droid), but this didn't work.

My questions:
- What port do I need to use for the proxy?
- Which username and password should I set (Google Account?)?
- Is it even possible to use these server as Proxies?

Thanks and Best regards

**Comment by pelzvieh** [comment]
I'm not sure if I got the point. It seems you are trying to connect with OpenVPN to your smartphone running IPv6Droid? This is probably not going to work.
IPv6Droid itself is providing a tunnel transferring IPv6 packages through an IPv4 network.
It is not providing an endpoint for an OpenVPN tunnel, this would require an OpenVPN app.

**Comment by lordnik22** [comment]
Sorry, I have to clarify a bit more.

I have a OpenVPN-Server at my home and my ISP only gives me an IPv6 which makes my OpenVPN-Server only available over IPv6.
```
Phone                      Server
OpenVPN-Client -> OpenVPN-Server
```
What I try to configure is a Proxy. The OpenVPN-Client still connects to my OpenVPN-Server but over a Proxy. Which would be your IPv6 Server.
```
Phone                      Proxy             Server
OpenVPN-Client -> IPv6Droid -> OpenVPN-Server
```

- Is that possible?

**Comment by pelzvieh** [comment]
I'm afraid that is not possible, at least I'm lacking an idea how it would work. Android puts one big restriction on tunnel apps: not more than one of them can be active at any time. An OpenVPN app would want to create an encrypted tunnel service, therefore it would automatically stop the IPv6Droid tunnel - and no longer be able to reach its counterpart by IPv6.
You might want to consider two possible approaches:
- use an http proxy on an external host with both a fixed IPv4 address and IPv6 capability, in order to pass on the OpenVPN connection (from mobile via IPv4) to your OpenVPN endpoint via IPv6
- eliminate your VPN requirements by enabling all your required services with TLS and strong authentication.
The latter approach works fair enough for me and generally seems in line with the "zero trust" recommendation. However, your requirements may very well differ.
